// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPQdw7uQH3OVbr35QexxrjEd6SRWMeUE',
    appId: '1:761556044005:web:b09160b644430fb03aac0c',
    messagingSenderId: '761556044005',
    projectId: 'dima-project-968ce',
    authDomain: 'dima-project-968ce.firebaseapp.com',
    storageBucket: 'dima-project-968ce.appspot.com',
    measurementId: 'G-LCK8K3HH3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgmj2I7YqpJI730obq7ULlIfyh4hTytQ',
    appId: '1:761556044005:android:87ce2c7580d19a703aac0c',
    messagingSenderId: '761556044005',
    projectId: 'dima-project-968ce',
    storageBucket: 'dima-project-968ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOkTvIT2au24jxp4fXzY5IbHyNwgZtu_4',
    appId: '1:761556044005:ios:8783d365a505489c3aac0c',
    messagingSenderId: '761556044005',
    projectId: 'dima-project-968ce',
    storageBucket: 'dima-project-968ce.appspot.com',
    iosClientId: '761556044005-k9gevoj6ldoan8e5gq1b23f34oirue62.apps.googleusercontent.com',
    iosBundleId: 'it.polimi.dima.nicolovincenzo.dimaProject',
  );
}
